"use client";

import { useState } from "react";
import { Info, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * AI transparency panel — surfaces the model's rationale so users (and
 * government/university stakeholders) understand WHY a recommendation was made.
 */
export function AiTransparency({
  rationale,
  usedFallback,
}: {
  rationale: string;
  usedFallback?: boolean;
}) {
  const [open, setOpen] = useState(false);
  return (
    <div className="rounded-lg border bg-muted/40 text-sm">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center gap-2 p-3 text-left font-medium"
      >
        <Info className="h-4 w-4 text-primary" />
        Why this recommendation?
        <ChevronDown className={cn("ml-auto h-4 w-4 transition-transform", open && "rotate-180")} />
      </button>
      {open && (
        <div className="space-y-2 px-3 pb-3 text-muted-foreground">
          <p>{rationale || "No rationale was provided for this result."}</p>
          <p className="text-xs">
            Generated by {usedFallback ? "an offline heuristic (demo mode)" : "Gemini 2.5 Flash"}.
            Recommendations are guidance, not guarantees. You control your data and can revise inputs anytime.
          </p>
        </div>
      )}
    </div>
  );
}
