"use client";

import { useState } from "react";
import { Info, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";

export type Confidence = "high" | "medium" | "low";

const CONFIDENCE_STYLES: Record<Confidence, { dot: string; label: string }> = {
  high: { dot: "bg-emerald-500", label: "High confidence" },
  medium: { dot: "bg-amber-500", label: "Medium confidence" },
  low: { dot: "bg-red-500", label: "Low confidence" },
};

/**
 * AI explainability panel — surfaces WHY a recommendation was made, what
 * signals were detected, and how much to trust it. Used across all modules
 * so transparency is a product feature, not a footnote.
 */
export function AiTransparency({
  rationale,
  usedFallback,
  confidence,
  detectedSkills,
  factors,
  defaultOpen = false,
}: {
  rationale: string;
  usedFallback?: boolean;
  /** Defaults to "high" for model output, "medium" for the offline heuristic. */
  confidence?: Confidence;
  /** Signals the AI detected in the user's input (e.g. skills found in a CV). */
  detectedSkills?: string[];
  /** Bullet-point reasoning behind the recommendation. */
  factors?: string[];
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);
  const level: Confidence = confidence ?? (usedFallback ? "medium" : "high");
  const style = CONFIDENCE_STYLES[level];

  return (
    <div className="rounded-lg border bg-muted/40 text-sm">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center gap-2 p-3 text-left font-medium"
      >
        <Info className="h-4 w-4 shrink-0 text-primary" />
        Why this recommendation?
        <span className="ml-auto flex items-center gap-2">
          <span className="flex items-center gap-1.5 text-xs font-normal text-muted-foreground">
            <span className={cn("h-2 w-2 rounded-full", style.dot)} />
            {style.label}
          </span>
          <ChevronDown className={cn("h-4 w-4 transition-transform", open && "rotate-180")} />
        </span>
      </button>
      {open && (
        <div className="space-y-3 px-3 pb-3 text-muted-foreground">
          <p>{rationale || "No rationale was provided for this result."}</p>

          {detectedSkills && detectedSkills.length > 0 && (
            <div>
              <p className="mb-1.5 text-xs font-medium uppercase tracking-wide">Detected signals</p>
              <div className="flex flex-wrap gap-1.5">
                {detectedSkills.map((s) => (
                  <Badge key={s} variant="secondary">
                    {s}
                  </Badge>
                ))}
              </div>
            </div>
          )}

          {factors && factors.length > 0 && (
            <div>
              <p className="mb-1.5 text-xs font-medium uppercase tracking-wide">How this was decided</p>
              <ul className="list-inside list-disc space-y-1">
                {factors.map((f, i) => (
                  <li key={i}>{f}</li>
                ))}
              </ul>
            </div>
          )}

          <p className="text-xs">
            Generated by {usedFallback ? "an offline heuristic (demo mode)" : "Gemini 2.5 Flash"}.
            Recommendations are guidance, not guarantees. You control your data and can revise inputs anytime.
          </p>
        </div>
      )}
    </div>
  );
}
