import type { Language } from "@/types";

/**
 * Lightweight UI dictionaries for Uzbek (Latin), Russian, and English.
 * Covers navigation, auth, dashboard, and onboarding copy — module content
 * is generated by the AI in the user's chosen language.
 */

const en = {
  nav: {
    dashboard: "Dashboard",
    career: "Career Navigator",
    learning: "Adaptive Learning",
    tutor: "AI Tutor",
    educator: "Educator Copilot",
    jobs: "Job Matchmaker",
    insights: "Market Insights",
  },
  common: {
    signIn: "Sign in",
    signUp: "Create account",
    signOut: "Sign out",
    tryDemo: "Try the demo",
    demoUser: "Demo student",
    getStarted: "Get started",
    language: "Language",
    theme: "Theme",
    open: "Open",
    loading: "Loading…",
  },
  landing: {
    heroTitle: "From your resume to a real job —",
    heroAccent: "in your language.",
    heroSub:
      "SkillBridge AI assesses your skills, builds a personalized multilingual learning roadmap, and matches you to internships and jobs in Uzbekistan's digital economy.",
    ctaPrimary: "Get my Readiness Score",
    ctaDemo: "Try the live demo",
    onboardingTitle: "Built for Uzbekistan's digital decade",
    onboardingSub:
      "One million IT professionals by 2030 starts with knowing where you stand today. SkillBridge works in Uzbek, Russian, and English — from Tashkent to Nukus.",
    steps: [
      { title: "Upload your CV", desc: "PDF, DOCX, or plain text — AI extracts your skills in seconds." },
      { title: "Get your roadmap", desc: "A readiness score and step-by-step plan toward IT Park-ready roles." },
      { title: "Match to real work", desc: "Internships and junior roles across Uzbekistan's growing tech sector." },
    ],
  },
  auth: {
    welcomeBack: "Welcome back",
    loginSub: "Sign in to continue your learning journey.",
    createTitle: "Create your account",
    createSub: "Free for students, jobseekers, and educators in Uzbekistan.",
    fullName: "Full name",
    email: "Email",
    password: "Password",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    demoHint: "No signup needed — explore with a seeded student profile.",
    cloudOff: "Cloud accounts are not configured in this environment. Use the one-click demo below.",
  },
  dashboard: {
    welcome: "Welcome back",
    subtitle: "Here's your progress across SkillBridge.",
    progressSummary: "Progress summary",
    latestReadiness: "Latest readiness",
    assessments: "Assessments",
    courses: "Courses created",
    tutorSessions: "Tutor sessions",
    recentAssessments: "Recent assessments",
    savedRoadmap: "Your latest roadmap",
    tutorActivity: "Tutor activity",
    generatedCourses: "Generated courses",
    emptyAssessments: "No assessments yet — analyze your CV to get your first readiness score.",
    emptyRoadmap: "Your personalized roadmap will appear here after your first CV analysis.",
    emptyTutor: "Ask the AI tutor anything — in Uzbek, Russian, or English.",
    emptyCourses: "Generate a full course with one prompt in the Educator Copilot.",
    analyzeCta: "Analyze my CV",
    askTutorCta: "Ask the tutor",
    createCourseCta: "Create a course",
    sinceLast: "since last assessment",
    steps: "steps",
  },
} as const;

export type Dict = {
  nav: Record<keyof typeof en.nav, string>;
  common: Record<keyof typeof en.common, string>;
  landing: Omit<Record<keyof typeof en.landing, string>, "steps"> & {
    steps: ReadonlyArray<{ title: string; desc: string }>;
  };
  auth: Record<keyof typeof en.auth, string>;
  dashboard: Record<keyof typeof en.dashboard, string>;
};

const uz: Dict = {
  nav: {
    dashboard: "Boshqaruv paneli",
    career: "Karyera navigatori",
    learning: "Moslashuvchan ta'lim",
    tutor: "AI repetitor",
    educator: "O'qituvchi yordamchisi",
    jobs: "Ish topish",
    insights: "Mehnat bozori",
  },
  common: {
    signIn: "Kirish",
    signUp: "Ro'yxatdan o'tish",
    signOut: "Chiqish",
    tryDemo: "Demo rejimni sinash",
    demoUser: "Demo talaba",
    getStarted: "Boshlash",
    language: "Til",
    theme: "Mavzu",
    open: "Ochish",
    loading: "Yuklanmoqda…",
  },
  landing: {
    heroTitle: "Rezyumeingizdan haqiqiy ishgacha —",
    heroAccent: "o'z tilingizda.",
    heroSub:
      "SkillBridge AI ko'nikmalaringizni baholaydi, shaxsiy ko'p tilli o'quv yo'l xaritasini tuzadi va sizni O'zbekiston raqamli iqtisodiyotidagi amaliyot va ish o'rinlariga moslashtiradi.",
    ctaPrimary: "Tayyorgarlik balimni olish",
    ctaDemo: "Jonli demoni sinash",
    onboardingTitle: "O'zbekistonning raqamli o'n yilligi uchun yaratilgan",
    onboardingSub:
      "2030-yilgacha 1 million IT mutaxassis — bugun qayerda turganingizni bilishdan boshlanadi. SkillBridge o'zbek, rus va ingliz tillarida ishlaydi — Toshkentdan Nukusgacha.",
    steps: [
      { title: "CV yuklang", desc: "PDF, DOCX yoki matn — AI ko'nikmalaringizni soniyalarda aniqlaydi." },
      { title: "Yo'l xaritangizni oling", desc: "Tayyorgarlik bali va IT Park darajasidagi kasblarga bosqichma-bosqich reja." },
      { title: "Haqiqiy ishga moslashing", desc: "O'zbekiston texnologiya sektoridagi amaliyot va junior lavozimlar." },
    ],
  },
  auth: {
    welcomeBack: "Xush kelibsiz",
    loginSub: "O'qishni davom ettirish uchun tizimga kiring.",
    createTitle: "Hisob yarating",
    createSub: "O'zbekistondagi talabalar, ish izlovchilar va o'qituvchilar uchun bepul.",
    fullName: "To'liq ism",
    email: "Email",
    password: "Parol",
    noAccount: "Hisobingiz yo'qmi?",
    haveAccount: "Hisobingiz bormi?",
    demoHint: "Ro'yxatdan o'tish shart emas — tayyor talaba profili bilan sinab ko'ring.",
    cloudOff: "Bulutli hisoblar bu muhitda sozlanmagan. Quyidagi bir bosishli demodan foydalaning.",
  },
  dashboard: {
    welcome: "Xush kelibsiz",
    subtitle: "SkillBridge bo'ylab jarayoningiz.",
    progressSummary: "Umumiy natija",
    latestReadiness: "So'nggi tayyorgarlik",
    assessments: "Baholashlar",
    courses: "Yaratilgan kurslar",
    tutorSessions: "Repetitor suhbatlari",
    recentAssessments: "So'nggi baholashlar",
    savedRoadmap: "So'nggi yo'l xaritangiz",
    tutorActivity: "Repetitor faolligi",
    generatedCourses: "Yaratilgan kurslar",
    emptyAssessments: "Hozircha baholash yo'q — birinchi balingiz uchun CV tahlil qiling.",
    emptyRoadmap: "Birinchi CV tahlilidan keyin shaxsiy yo'l xaritangiz shu yerda paydo bo'ladi.",
    emptyTutor: "AI repetitordan istalgan savolni so'rang — o'zbek, rus yoki ingliz tilida.",
    emptyCourses: "O'qituvchi yordamchisida bitta so'rov bilan to'liq kurs yarating.",
    analyzeCta: "CV tahlil qilish",
    askTutorCta: "Repetitordan so'rash",
    createCourseCta: "Kurs yaratish",
    sinceLast: "oldingi baholashdan beri",
    steps: "bosqich",
  },
};

const ru: Dict = {
  nav: {
    dashboard: "Панель управления",
    career: "Карьерный навигатор",
    learning: "Адаптивное обучение",
    tutor: "AI-репетитор",
    educator: "Помощник преподавателя",
    jobs: "Подбор вакансий",
    insights: "Рынок труда",
  },
  common: {
    signIn: "Войти",
    signUp: "Создать аккаунт",
    signOut: "Выйти",
    tryDemo: "Попробовать демо",
    demoUser: "Демо-студент",
    getStarted: "Начать",
    language: "Язык",
    theme: "Тема",
    open: "Открыть",
    loading: "Загрузка…",
  },
  landing: {
    heroTitle: "От резюме до реальной работы —",
    heroAccent: "на вашем языке.",
    heroSub:
      "SkillBridge AI оценивает ваши навыки, строит персональную многоязычную дорожную карту обучения и подбирает стажировки и вакансии в цифровой экономике Узбекистана.",
    ctaPrimary: "Узнать мой балл готовности",
    ctaDemo: "Открыть живое демо",
    onboardingTitle: "Создано для цифрового десятилетия Узбекистана",
    onboardingSub:
      "Миллион IT-специалистов к 2030 году начинается с понимания, где вы сейчас. SkillBridge работает на узбекском, русском и английском — от Ташкента до Нукуса.",
    steps: [
      { title: "Загрузите CV", desc: "PDF, DOCX или текст — AI извлечёт ваши навыки за секунды." },
      { title: "Получите дорожную карту", desc: "Балл готовности и пошаговый план к ролям уровня IT Park." },
      { title: "Найдите реальную работу", desc: "Стажировки и junior-позиции в растущем tech-секторе Узбекистана." },
    ],
  },
  auth: {
    welcomeBack: "С возвращением",
    loginSub: "Войдите, чтобы продолжить обучение.",
    createTitle: "Создайте аккаунт",
    createSub: "Бесплатно для студентов, соискателей и преподавателей Узбекистана.",
    fullName: "Полное имя",
    email: "Email",
    password: "Пароль",
    noAccount: "Ещё нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    demoHint: "Без регистрации — изучите платформу с готовым профилем студента.",
    cloudOff: "Облачные аккаунты не настроены в этой среде. Используйте демо в один клик ниже.",
  },
  dashboard: {
    welcome: "С возвращением",
    subtitle: "Ваш прогресс в SkillBridge.",
    progressSummary: "Сводка прогресса",
    latestReadiness: "Последняя готовность",
    assessments: "Оценки",
    courses: "Создано курсов",
    tutorSessions: "Сессии с репетитором",
    recentAssessments: "Недавние оценки",
    savedRoadmap: "Ваша последняя дорожная карта",
    tutorActivity: "Активность репетитора",
    generatedCourses: "Созданные курсы",
    emptyAssessments: "Пока нет оценок — проанализируйте CV, чтобы получить первый балл готовности.",
    emptyRoadmap: "Персональная дорожная карта появится здесь после первого анализа CV.",
    emptyTutor: "Спросите AI-репетитора о чём угодно — на узбекском, русском или английском.",
    emptyCourses: "Создайте полный курс одним запросом в Помощнике преподавателя.",
    analyzeCta: "Анализ CV",
    askTutorCta: "Спросить репетитора",
    createCourseCta: "Создать курс",
    sinceLast: "с прошлой оценки",
    steps: "шагов",
  },
};

export const DICTIONARIES: Record<Language, Dict> = { en, uz, ru };

export const LANGUAGE_LABELS: Record<Language, string> = {
  uz: "🇺🇿 O'zbekcha",
  ru: "🇷🇺 Русский",
  en: "🇬🇧 English",
};
